def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
    'UNSTABLE': 'warning'
]
pipeline {
    agent any
    tools {
        maven 'MAVEN_3.9'
        jdk 'jdk_17'
    }

    environment {
        registryCredentials = 'ecr:ap-southeast-1:awscreds'
        imageName = "878221067568.dkr.ecr.ap-southeast-1.amazonaws.com/vprofileappimg"
        vprofileRegistry = "https://878221067568.dkr.ecr.ap-southeast-1.amazonaws.com"
    }

    stages {

        stage('Fetch code') {
            steps {
                git branch: 'docker', url: 'https://github.com/hkhcoder/vprofile-project.git'
            }
        }
        stage('Unit Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn install -DskipTests'
            }
            post {
                success {
                    echo 'Archiving artifacts...'
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Checkstyle Analysis') {
            steps {
                sh 'mvn checkstyle:checkstyle'
            }
        }
        stage("Sonar Code analysis") {
            environment {
                scannerHome = tool 'sonar6.2'
            }
            steps {
              withSonarQubeEnv('sonarserver') {
                sh '''${scannerHome}/bin/sonar-scanner \
                  -Dsonar.projectName=vprofile \
                  -Dsonar.projectVersion=1.0 \
                  -Dsonar.projectKey=vprofile \
                  -Dsonar.sources=src \
                  -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                  -Dsonar.junit.reportPaths=target/surefire-reports \
                  -Dsonar.jacoco.reportPaths=target/jacoco.exec \
                  -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
                '''
              }
            }
          }
        stage("Quality Gate") {
            steps {
              timeout(time: 1, unit: 'HOURS') {
                waitForQualityGate abortPipeline: true
              }
            }
        }
        stage ('Build App Image') {
            steps {
                script {
                    dockerImage = docker.build( imageName + ":$BUILD_NUMBER", "./Docker-files/app/multistage/" )
                }
            }
        }
        stage ('Upload App Image') {
            steps {
                script {
                    docker.withRegistry( vprofileRegistry, registryCredentials ) {
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push("latest")
                    }
                }
            }
        }
        stage ('Remove Container Images') {
            steps {
                sh 'docker rmi -f $(docker images -a -q)'
            }

        }
    }
    post {
        always {
            echo 'Slack Notificaton...'
            slackSend channel: '#devopscicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}
